version: '3.8'

networks:
  youtube-trending-data-analysis:
    name: youtube-trending-data-analysis
    external: true

services:
  mb-postgres:
    image: postgres:17.7
    container_name: mb-postgres
    environment:
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
      POSTGRES_DB: metabase
    volumes:
      - ./metabase-data:/var/lib/postgresql/data
    networks:
      - youtube-trending-data-analysis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      retries: 5

  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: mb-postgres
    depends_on:
      - mb-postgres
    networks:
      - youtube-trending-data-analysis
    volumes:
      - ./metabase-data:/metabase-data

volumes:
  metabase-db-volume:
